### ISSUE TITLE
Twtxt support

### ISSUE THREAD

**Issue by prologic** [n0madic/twitter2rss#3]
Hi 👋

First of all, great project and demo service (_I'm using it now! hope you don't mind!_).

Couple of questions:

- What is the license of your code?
- Would you considering working with me to add twtxt support?

My goal is to add support for Twitter handles/timelines to my twtxt feeds services at [feeds.twtxt.net](https://feeds.twtxt.net) which is used as an external source of RSS/Atom (_and now Twitter_) feeds for Yarn.social pods (See https://git.mills.io/yarnsocial/yarn)

**Comment by n0madic** [comment]
Hello.
This is a very simple service without a license (may be in the public domain), essentially a wrapper around my [twitter-scraper](https://github.com/n0madic/twitter-scraper) package with MIT license. I think you'd better use it directly.

**Comment by prologic** [comment]
> Hello.
> This is a very simple service without a license (may be in the public domain), essentially a wrapper around my [twitter-scraper](https://github.com/n0madic/twitter-scraper) package with MIT license. I think you'd better use it directly.

Yeah I saw it's dependency. I've only added two Twitter account sto your services so far, I promise I won't add anymore! 😀

Do you mine if I mostly borrow code from here and incorporate it into my [feeds.twtxt.net](https://feeds.twtxt.net) service (Source code: https://git.mills.io/yarnsocial/rss2twtxt -- Although I should probably rename that project and it's codebase!)

**Comment by n0madic** [comment]
use the code as you need. there are no restrictions here

**Comment by prologic** [comment]
Thank you 🙇‍♂️
