### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by vtmocanu** [n0madic/twitter2rss#4]
Thanks for sharing this!
I've been looking for something like this, rssbridge is unstable with twitter, nitter also has some capacity issues.
Hopefully this will work as expected.

**Comment by n0madic** [comment]
You're welcome. There are no restrictions.

**Comment by gety9** [comment]
@WladyX are you still using this project to get twitter rss? How is your experience / how stable is it?

**Comment by vtmocanu** [comment]
meh, mixed feelings, i get very often: `Limit exceeded`, but have not searched/found anything else more stable.
