### ISSUE TITLE
Title issue

### ISSUE THREAD

**Issue by Bamboozul** [n0madic/twitter2rss#5]
Hi,

If a special character such as ":" or "!" exists, the title is not fully captured.

e.g.
 "Hirogaru Sky" should be "Hirogaru Sky! Precure — Episode 03"
"Majutsushi Orphen Hagure Tabi" should be "Majutsushi Orphen Hagure Tabi: Urbanrama-hen"
"Tsurune" should be "Tsurune: Tsunagari no Issha — Episode 08"

![Screenshot 2023-02-26 160146](https://user-images.githubusercontent.com/101983929/221415355-6a0a1d69-8529-45c3-93bf-1f1e7ca3e2ae.png)
![Screenshot 2023-02-26 160203](https://user-images.githubusercontent.com/101983929/221415359-d176231b-f413-40de-b695-1cd58dd6be8a.png)

**Comment by n0madic** [comment]
Tweets don't have a title so I just have to somehow [extract](https://github.com/n0madic/twitter2rss/blob/master/twitter2rss.go#L51) the first sentence from the tweet and use that as the title...
Its not bug

**Comment by Bamboozul** [comment]
> Tweets don't have a title so I just have to somehow [extract](https://github.com/n0madic/twitter2rss/blob/master/twitter2rss.go#L51) the first sentence from the tweet and use that as the title... Its not bug

Yeah, I know tweets don't have titles, but I couldn't think of anything else to say. And your RSS is the only one that considers the first sentence to be a title, which is exactly what I'm looking for.

Also, could you add another filter to exclude retweets?

**Comment by n0madic** [comment]
it is possible, but it needs free time..

**Comment by Bamboozul** [comment]
> it is possible, but it needs free time..

Sure, whenever you have time.
