### ISSUE TITLE
The demo is not working

### ISSUE THREAD

**Issue by Bamboozul** [n0madic/twitter2rss#7]
When you press the "GET RSS" button, the [demo site](https://twitter2rss.nomadic.name/) keeps loading until you reach the cloudflare timeout screen.

 
![Screenshot 2023-06-12 230048](https://github.com/n0madic/twitter2rss/assets/101983929/7460b025-a6cb-4ec1-8179-cafc87769d8b)

**Comment by n0madic** [comment]
Due to the high popularity, unfortunately, constantly get an error
```
429 Too Many Requests: {"code":88,"message":"Rate limit exceeded."}
```
